<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_driver_model extends CI_Model
{

    public $table = 'data_driver';
    public $id = 'id_driver';
    public $id_user = 'id_user';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id_user, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_driver', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('jenis_kendaraan', $q);
	$this->db->or_like('no_plat', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('lat', $q);
	$this->db->or_like('lng', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_driver', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('jenis_kendaraan', $q);
	$this->db->or_like('no_plat', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('lat', $q);
	$this->db->or_like('lng', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id_user, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id_user, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_driver_model.php */
/* Location: ./application/models/Data_driver_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-06 09:46:19 */
/* http://harviacode.com */